<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
   <PropertyGroup>
    <TargetFramework>net8.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>

    <!-- IMPORTANT pour GitHub Pages : désactive les threads WASM (COOP/COEP impossibles sur Pages) -->
    <WasmEnableThreads>false</WasmEnableThreads>

    <!-- Garde le trimming désactivé (plus stable pour Avalonia/Skia en WASM) -->
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PizthieR\PizthieR.csproj" />
  </ItemGroup>
</Project>
